--- 
author: 
  - Martin Thurn <mthurn@cpan.org>
build_requires: 
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Net-Address-Ethernet
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Data::Dumper: 0
requires: 
  Net::Domain: 0
  Net::Ifconfig::Wrapper: 0
  Regexp::Common: 0
  Sys::Hostname: 0
  perl: 5.004
version: 1.110
